- hosts: centosnode
  remote_user: vagrant
  become: true
  become_method: sudo
  become_user: root
  tasks:
  - name: Install httpd and php
    yum: name="{{ item }}" state=present
    with_items:
    - httpd
    - php
    - php-mysql

  - name: Install web role specific dependencies
    yum: name="{{ item }}" state=installed
    with_items:
    - git

  - name: Start & Enable Apache Server to start on boot
    service: name=httpd state=started enabled=yes

  - name: Enable the firewall port for Apache
    firewalld: port=8081/tcp permanent=true state=enabled immediate=yes