---
- hosts: web
  remote_user: vagrant
  become: true
  become_method: sudo
  become_user: root
  tasks:
  - name: Install Collectd
    apt: 
     name:
      - collectd 
     state: present
    when: ansible_os_family == "Debian"
    
  - name: Install Collectd
    apt: 
     name:
      - collectd-utils
     state: present
    when: ansible_os_family == "Debian"

  - name: Collectd CentOS
    yum:
     name:
      - epel-release.noarch
      - collectd
     state: present
    when: ansible_os_family == "RedHat"