---
- hosts: ubuntunode
  tasks:
  - name: Create simeplage Folder
    file:
     path: /var/www/simplepage
     state: directory
    become: yes
  - name : Copy Simple Php Page
    copy:
     src: /home/vagrant/share/simplepage.php
     dest: /var/www/html/index.php
     owner: vagrant
     group: vagrant
     mode: '0644'
    become: yes
  - name: Delete index.html
    file:
     path: /var/www/html/index.html
     state: absent
  - name: Change Listen port
    lineinfile:
     path: /etc/apache2/ports.conf
     regexp: '^Listen '
     line: 'Listen 8081'
     state: present
    become: yes
  - name: Change default conf
    lineinfile:
     path: /etc/apache2/sites-available/000-default.conf
     regexp: '^<VirtualHost \*:'
     line: '<VirtualHost *:8081>'
     state: present
    become: yes
  - name: Copy Conf
    copy:
     src: /home/vagrant/share/configuration.conf
     dest: /etc/apache2/sites-available/example.conf
    become: yes
  - name: Restart Apache
    service:
      name: apache2
      state: restarted