---
- hosts: ubuntunode
  tasks:
  - name: Install Apache2
    apt: pkg=apache2 state=present
    become: true
  - name: Start Apache
    service: name=apache2 state=started enabled=true
    become: true
  - name: Install MySql
    apt: pkg=mysql-server state=present
    become: true
  - name: Start Mysql
    service: name=mysql state=started enabled=true
  - name: Add repo for PHP
    become: true
    apt_repository:
      repo="ppa:ondrej/php"
  - name: Install Php
    become: true
    apt:
     name: 
      - php7.1-cli
      - php7.1-curl
      - php7.1-fpm
      - php7.1-intl
      - php7.1-mysql
     state: latest